using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Nekolpos.System;
using UnityEditor;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

namespace Nekolpos.EditorTools
{
    /// <summary>
    /// Builds a transform Avatar Mask from the clips owned by a selected Animation Track.
    /// This is editor-only support: it never changes clips, controllers, or runtime playback.
    /// </summary>
    public static class TimelineAvatarMaskGenerator
    {
        private const string MaskFolder = "Assets/Animation/AvatarMasks/AutoGenerated";
        private const string LogPrefix = "[Timeline Auto Mask]";

        [MenuItem("CONTEXT/AnimationTrack/Auto Generate Avatar Mask", false, 2000)]
        private static void AutoGenerateFromContext(MenuCommand command)
        {
            GenerateAndAssign(command.context as AnimationTrack);
        }

        [MenuItem("Tools/Nekolpos/Timeline/Auto Generate Avatar Mask for Selected Track", false, 220)]
        private static void AutoGenerateFromSelectedTrack()
        {
            GenerateAndAssign(Selection.activeObject as AnimationTrack);
        }

        [MenuItem("Tools/Nekolpos/Timeline/Auto Generate Avatar Mask for Selected Track", true)]
        private static bool ValidateAutoGenerateFromSelectedTrack()
        {
            return Selection.activeObject is AnimationTrack;
        }

        internal static bool TryGetAnimatedTransformPaths(
            AnimationTrack track,
            out HashSet<string> transformPaths,
            out string error)
        {
            transformPaths = new HashSet<string>(StringComparer.Ordinal);
            error = null;

            if (track == null)
            {
                error = "Animation Trackが選択されていません。";
                return false;
            }

            var clips = new HashSet<AnimationClip>();
            if (track.infiniteClip != null)
            {
                clips.Add(track.infiniteClip);
            }

            foreach (TimelineClip timelineClip in track.GetClips())
            {
                if (timelineClip.animationClip != null)
                {
                    clips.Add(timelineClip.animationClip);
                }
            }

            if (clips.Count == 0)
            {
                error = $"Animation Track '{track.name}' にAnimationClipがありません。";
                return false;
            }

            foreach (AnimationClip clip in clips)
            {
                foreach (EditorCurveBinding binding in AnimationUtility.GetCurveBindings(clip))
                {
                    if (IsLocalTransformBinding(binding))
                    {
                        transformPaths.Add(binding.path ?? string.Empty);
                    }
                }
            }

            if (transformPaths.Count == 0)
            {
                error = "AnimationClip内にTransform Animation Curveがありません。";
                return false;
            }

            return true;
        }

        internal static bool TryPopulateMask(
            AvatarMask mask,
            Transform animatorRoot,
            IEnumerable<string> animatedTransformPaths,
            out string error)
        {
            error = null;
            if (mask == null)
            {
                error = "Avatar Mask生成先を作成できません。";
                return false;
            }

            if (animatorRoot == null)
            {
                error = "Animator / Avatarのルートを特定できません。";
                return false;
            }

            var requiredTransforms = new HashSet<Transform>();
            var activeTransformPaths = new HashSet<string>(animatedTransformPaths, StringComparer.Ordinal);
            foreach (string path in activeTransformPaths)
            {
                Transform target = string.IsNullOrEmpty(path) ? animatorRoot : animatorRoot.Find(path);
                if (target == null)
                {
                    error = $"Animator '{animatorRoot.name}' にCurve対象Transform '{path}' がありません。";
                    return false;
                }

                for (Transform current = target; current != null; current = current.parent)
                {
                    requiredTransforms.Add(current);
                    if (current == animatorRoot)
                    {
                        break;
                    }
                }
            }

            if (requiredTransforms.Count == 0)
            {
                error = "Avatar Maskに登録するTransformを特定できません。";
                return false;
            }

            foreach (Transform transform in requiredTransforms
                         .OrderBy(transform => GetDepth(animatorRoot, transform))
                         .ThenBy(transform => AnimationUtility.CalculateTransformPath(transform, animatorRoot), StringComparer.Ordinal))
            {
                // recursive:false is essential: only the curve targets and their ancestors are registered.
                mask.AddTransformPath(transform, false);
            }

            for (int index = 0; index < mask.transformCount; index++)
            {
                // Ancestors are structural entries only. Timeline actually owns only transforms with curves.
                mask.SetTransformActive(index, activeTransformPaths.Contains(mask.GetTransformPath(index)));
            }

            return true;
        }

        internal static void AssignMask(AnimationTrack track, AvatarMask mask)
        {
            Undo.RecordObject(track, "Assign Timeline Avatar Mask");
            track.avatarMask = mask;
            track.applyAvatarMask = true;
            EditorUtility.SetDirty(track);
        }

        private static void GenerateAndAssign(AnimationTrack track)
        {
            if (!TryGetAnimatedTransformPaths(track, out HashSet<string> paths, out string error))
            {
                Debug.LogWarning($"{LogPrefix} {error}");
                return;
            }

            Animator animator = FindAnimatorRoot(track, paths, out error);
            if (animator == null)
            {
                Debug.LogWarning($"{LogPrefix} {error}");
                return;
            }

            EnsureFolder(MaskFolder);
            string maskPath = $"{MaskFolder}/{GetMaskAssetName(track)}.mask";
            AvatarMask existing = AssetDatabase.LoadAssetAtPath<AvatarMask>(maskPath);
            if (existing != null)
            {
                int choice = EditorUtility.DisplayDialogComplex(
                    "Auto Generate Avatar Mask",
                    $"既存Maskがあります。\n{maskPath}\n\n更新すると現在のTransform設定を解析結果で置き換えます。",
                    "更新して適用",
                    "既存Maskを適用",
                    "キャンセル");
                if (choice == 2)
                {
                    return;
                }

                if (choice == 1)
                {
                    AssignMask(track, existing);
                    AssetDatabase.SaveAssets();
                    Debug.Log($"{LogPrefix} 既存MaskをTrack '{track.name}' へ適用しました: {maskPath}");
                    return;
                }
            }

            // Build into a fresh mask first, so a failed analysis never damages an existing asset.
            AvatarMask generatedMask = new AvatarMask();
            if (!TryPopulateMask(generatedMask, animator.transform, paths, out error))
            {
                UnityEngine.Object.DestroyImmediate(generatedMask);
                Debug.LogWarning($"{LogPrefix} {error}");
                return;
            }

            AvatarMask mask;
            if (existing == null)
            {
                generatedMask.name = GetMaskAssetName(track);
                AssetDatabase.CreateAsset(generatedMask, maskPath);
                // AvatarMask can clear its in-memory name during CreateAsset on some Unity versions.
                generatedMask.name = GetMaskAssetName(track);
                EditorUtility.SetDirty(generatedMask);
                mask = generatedMask;
                Undo.RegisterCreatedObjectUndo(mask, "Create Timeline Avatar Mask");
            }
            else
            {
                Undo.RecordObject(existing, "Update Timeline Avatar Mask");
                EditorUtility.CopySerialized(generatedMask, existing);
                UnityEngine.Object.DestroyImmediate(generatedMask);
                existing.name = GetMaskAssetName(track);
                EditorUtility.SetDirty(existing);
                mask = existing;
            }

            AssignMask(track, mask);
            AssetDatabase.SaveAssets();
            Selection.activeObject = track;
            EditorGUIUtility.PingObject(mask);
            Debug.Log($"{LogPrefix} Maskを生成・適用しました: Track='{track.name}', Animator='{animator.name}', Transform数={mask.transformCount}, Path='{maskPath}'");
        }

        private static Animator FindAnimatorRoot(AnimationTrack track, ICollection<string> paths, out string error)
        {
            error = null;

            foreach (PlayableDirector director in Resources.FindObjectsOfTypeAll<PlayableDirector>())
            {
                if (!director.gameObject.scene.IsValid() || director.playableAsset != track.timelineAsset)
                {
                    continue;
                }

                Animator boundAnimator = ExtractAnimator(director.GetGenericBinding(track));
                if (MatchesAllPaths(boundAnimator, paths))
                {
                    return boundAnimator;
                }
            }

            Animator selectedAnimator = GetSelectedAnimator();
            if (MatchesAllPaths(selectedAnimator, paths))
            {
                return selectedAnimator;
            }

            foreach (CatPresentationModeController controller in Resources.FindObjectsOfTypeAll<CatPresentationModeController>())
            {
                if (controller.gameObject.scene.IsValid() && MatchesAllPaths(controller.NormalAnimator, paths))
                {
                    return controller.NormalAnimator;
                }
            }

            var candidates = Resources.FindObjectsOfTypeAll<Animator>()
                .Where(candidate => candidate.gameObject.scene.IsValid() && MatchesAllPaths(candidate, paths))
                .ToArray();
            if (candidates.Length == 1)
            {
                return candidates[0];
            }

            error = candidates.Length == 0
                ? "Curve Pathを満たすAnimator / Avatarのルートを特定できません。対象モデルを含むSceneを開いてください。"
                : $"Curve Pathを満たすAnimatorが複数あります ({string.Join(", ", candidates.Select(candidate => candidate.name))})。対象Animatorを選択してから実行してください。";
            return null;
        }

        private static Animator ExtractAnimator(UnityEngine.Object binding)
        {
            if (binding is Animator animator)
            {
                return animator;
            }

            if (binding is GameObject gameObject)
            {
                return gameObject.GetComponent<Animator>();
            }

            return binding is Component component ? component.GetComponent<Animator>() : null;
        }

        private static Animator GetSelectedAnimator()
        {
            foreach (UnityEngine.Object selected in Selection.objects)
            {
                if (selected is GameObject gameObject)
                {
                    Animator animator = gameObject.GetComponentInChildren<Animator>(true);
                    if (animator != null)
                    {
                        return animator;
                    }
                }
                else if (selected is Component component)
                {
                    Animator animator = component.GetComponentInChildren<Animator>(true);
                    if (animator != null)
                    {
                        return animator;
                    }
                }
            }

            return null;
        }

        private static bool MatchesAllPaths(Animator animator, IEnumerable<string> paths)
        {
            if (animator == null)
            {
                return false;
            }

            foreach (string path in paths)
            {
                if (!string.IsNullOrEmpty(path) && animator.transform.Find(path) == null)
                {
                    return false;
                }
            }

            return true;
        }

        private static bool IsLocalTransformBinding(EditorCurveBinding binding)
        {
            if (binding.type != typeof(Transform))
            {
                return false;
            }

            string property = binding.propertyName;
            return property.StartsWith("m_LocalPosition", StringComparison.Ordinal)
                   || property.StartsWith("localPosition", StringComparison.Ordinal)
                   || property.StartsWith("m_LocalRotation", StringComparison.Ordinal)
                   || property.StartsWith("localRotation", StringComparison.Ordinal)
                   || property.StartsWith("m_LocalEulerAngles", StringComparison.Ordinal)
                   || property.StartsWith("localEulerAngles", StringComparison.Ordinal)
                   || property.StartsWith("m_LocalScale", StringComparison.Ordinal)
                   || property.StartsWith("localScale", StringComparison.Ordinal);
        }

        private static int GetDepth(Transform root, Transform transform)
        {
            int depth = 0;
            for (Transform current = transform; current != null && current != root; current = current.parent)
            {
                depth++;
            }

            return depth;
        }

        private static string GetMaskAssetName(AnimationTrack track)
        {
            TimelineAsset timeline = track.timelineAsset as TimelineAsset;
            string prefix = timeline != null ? timeline.name : "Timeline";
            return $"{SanitizeFileName(prefix)}_{SanitizeFileName(track.name)}_Mask";
        }

        private static string SanitizeFileName(string value)
        {
            char[] invalid = Path.GetInvalidFileNameChars();
            return new string(value.Select(character =>
                Array.IndexOf(invalid, character) >= 0 || character == '/' || character == '\\' ? '_' : character).ToArray());
        }

        private static void EnsureFolder(string folder)
        {
            string[] segments = folder.Split('/');
            string current = segments[0];
            for (int index = 1; index < segments.Length; index++)
            {
                string next = $"{current}/{segments[index]}";
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, segments[index]);
                }

                current = next;
            }
        }
    }
}
