# 2026-09-08: Normal_Cat の非Play時の姿勢
# Assets/Scripts/Editor/NormalCatEditorPoseMenu.cs を追加。
# Tools > Nekolpos > Normal Cat > Restore Saved Idle Pose で、Animation/Timeline
# プレビューを終了し、Normal_Cat の通常Controller内の CatSimple_Lie_belly_loop_1
# の0秒をシーンのボーン姿勢として記録する。ルートの配置・回転・スケールは維持。
# OP_Catの姿勢、AnimationClip、Prefab本体は変更しない。Undo対応。
# シーンは自動保存しない。変更を確認した後にシーンを保存する。
# Verify Selection Stability は Normal_Cat -> OP_Cat の選択切替前後でボーンの
# 位置・回転が不変か検証し、元の選択を復元してConsoleへ結果を出力する。
#
# 2026-09-08: 会話CSVの明示的なTimelineシーケンス制御
# Animation列: timeline_sequence:MawStart / timeline_sequence:MawEnd
# MawStartでStartを1回再生し、LoopをEnd指定まで継続。次行・次会話だけでは終了しない。
# MawEndでStart/Loopを中断しEndを1回再生、通常伏せ姿勢と開始前のルート配置へ復帰。
# 各命令は行の表示開始時に実行し、テキスト表示・会話入力をブロックしない。
# 同じStartの重複はStart/Loop中は無視。End重複は再始動しない。未開始Endは何もしない。
# 別IDのStartは現在の演出を終了して新規開始。不明ID・不正設定はエラーを出して保持。
# DialogueTimelineSequenceController.cs: 3本のTimeline登録、明示状態遷移、
# Normal_CatへのAnimationTrackバインド、既存待機・視線制御の一時停止/復元を担当。
# 対応トラックは猫用AnimationTrackのみ。カメラ・Audio・Signal等は未対応で検証エラー。
# DialogueManager.PrepareLineDirectivesから同じGameObjectの上記コンポーネントを呼ぶ。
# DialogueTimelineSequenceSetup.cs: Tools/Nekolpos/Timeline Sequences/Configure Maw
# で既存MawStart/MawLoop/MawEndを登録。既存の他IDを保持し、会話本文は作成・変更しない。
# CatPresentationModeController.ResumeIdleAfterTimelineで入力UIを変えず通常待機を再開。
# DialogueTimelineSequenceTests.cs: 書式、不正指定、Start/Loop/End、途中End、
# 重複命令、ID不一致、無効化とルート復帰を検証。
#
# 2026-09-10: 会話Timelineの描画時上書き・視線復帰を修正
# 手動DirectorをUpdateで評価すると、その後の通常Animator評価で待機姿勢へ戻っていた。
# DialogueTimelineSequenceControllerはLateUpdateで評価し、描画時に演出姿勢を保持する。
# 視線のLateUpdate（実行順10000）はその後に実行する。
# SequencesのKeep Look At During Timelineで演出ごとに視線継続を設定（初期値オフ）。
# オフ時は視線コンポーネントと対応RigBuilderを一時停止。終了時は通常姿勢・ルートを
# 戻してから再有効化する。ResetToDefaultによる視線方式・軸・ターゲットの初期化は行わない。
# CatAnimationRuntime.ResumeIdleAfterTimelineは視線・入力UIを変えず待機ループのみ再開する。
# ID00450はPattern1のOrder3でMawStart、Order4でMawEnd。他Patternには命令なし。
# 手順書: docs/DialogueTimelineAuthoring.md。CSV保存後は暗号化変換とPlay再開始が必要。
# 既存テストにRecorded Clipの口/首曲線評価、Animator評価後のLateUpdate反映、姿勢復帰を追加。
# 2026-09-11: Sequence.phaseTransitionSeconds（初期値0.12秒）で、Start→Loop、
# Loop周回、Loop→End、End→通常待機の骨姿勢をsmoothstep補間する。スキンメッシュの骨だけを
# 保持するため、視線ON時もGeneratedNekomataLookAimTargetなどの注視補助Transformは
# 変えない。ID00450の実機確認でStart→Loop時の首位置維持と視線対象参照の維持を確認。
# 視線OFFはRig/RigBuilderを無効化せず、NekomataLookRigControllerの外部ウェイトを
# phaseTransitionSecondsで1→0、終了後0→1へフェードする。注視対象・追従の平滑化状態を
# 保持するため、Start開始時とEnd終了後の頭・目の一フレーム切替を避ける。
#
# 2026-09-11: 1時間の操作性・安定性改善（検証中）
# OpenBetaPauseMenuController: メニューに背景遮蔽と閉じるボタンを追加。
# メニューアイコンは64x64のUI領域。背景タップでも閉じる。開く前のtimeScaleを厳密に復元。
# ChatUIController.SetMenuInputBlockedによりメニュー中の会話送り・外部IME送信・選択を抑止。
# シーン参照・音源一覧の再探索を非スケール時間1秒間隔に制限。音切替時は即時探索・反映。
# 各音声Controllerは再生前に保存済みミュートを反映し、動的生成時の音漏れを防ぐ。
# UIStyle: Button ColorTintの二重乗算を解消。通常テーマのボタン文字は濃色、不穏テーマは明色。
# LogWindowPanel: LogIdごとに表示行を保持し、変更・追加・削除された行だけを作り直す。
# 最新付近では追従、それ以外ではスクロール位置を保持。開いた直後は最新へ移動。
# ConversationDataLoader: CSVの本文セル内改行は本文として保持。配列JSON・|区切りは維持。
# UiInteractionRegressionTests.csを追加: ポーズ中入力、解除・無効化時の復元、音量設定、文字コントラスト。
# 既存テストの古い長音/濁点除去の期待値を現在の保持仕様へ同期。未登録漢字は推測変換しない。
# 詳細な変更・検証記録は docs/ImprovementSession-20260911.md に記載する。
# 2026-09-15: 猫Presentation状態とTimeline共通入口
# CatPresentationModeControllerはOpeningに加えてIdle/Conversation/Timelineを公開し、
# 既存のNormalConversation/Event名はシーン互換の別名として保持する。Timeline開始時に
# 直前のIdleまたはConversationを保存し、DialogueTimelineSequenceControllerの
# BeginTimelinePresentation/ResumeIdleAfterTimeline経由で終了・中断・無効化後に自動復帰する。
# DialogueTimelineSequenceController.PlayTimeline(TimelineAsset, keepLookAtDuringTimeline,
# phaseTransitionSeconds)を外部会話・イベント用の単体Timeline共通入口とする。
# 既存のtimeline_sequenceのStart/Loop/End形式、AnimationTrack制限、姿勢補間、視線制御は維持。
# 開始・正常終了・中断は[DialogueTimelineSequence]ログで確認できる。
# 2026-09-16: Timeline中の通常Animator継続
# Timeline演出中も通常Animatorを稼働させ、呼吸・瞬き等の待機表現は維持する。
# AnimationTrackには演技対象だけを含むAvatar Maskを設定し、競合する視線や別演出だけを
# 2026-09-16: Timeline Animation Track Avatar Mask自動生成
# Tools/Nekolpos/TimelineのAuto Generate Avatar Maskは、選択AnimationTrackの有限Clipと
# Infinite ClipからTransform位置・回転・スケールCurveを解析する。Curve対象と必要な親だけを
# Transform Avatar Maskへ登録してTrackへ割り当て、Apply Avatar Maskを有効化する。生成Maskは
# Assets/Animation/AvatarMasks/AutoGeneratedに固定名で保存し、同名時は更新・再利用・中止を選ぶ。
# Sequence.additionalBehavioursToSuspendへ明示登録して停止する。Presentation/Runtimeを
# 一律に無効化して待機Animatorを止める方式は使用しない。
# KanjiReadingDictionaryのEditor限定フィンガープリントをUNITY_EDITORで囲み、
# WebGLプレイヤーの未使用フィールド警告を解消する。
# 2026-09-17: Timeline Editorプレビューの視線設定をRuntimeと共通化
# Timelineウィンドウで登録済みSequenceをプレビューする場合、同じSequenceの
# Keep Look At During Timelineを参照する。OFFのMawStart/MawLoop/MawEndでは、Runtimeで
# 視線ウェイトを下げる時と同じくTimeline開始直前の頭・目の向きを保持し、口・首位置には
# Timelineの記録姿勢を表示する。未登録Timelineは従来のEditor Preview設定を維持する。
# Normal_CatのEditor PreviewはRuntimeと同じRigBuilder/MultiAimConstraintを評価し、
# PlayerLookTargetのlocalOffset/worldOffsetを評価直前に同期する。保存済みRigがない猫のみ、
# 従来の直接ボーン回転へフォールバックする。
# PlayerLookTargetのEditモード用デバッグCollider破棄はDestroyImmediateを使用する。
# 2026-09-15: PsychologyReactionDialogue.csvを心理State別反応の正本として追加。
# context（FEELING/MORNING/DAY/EVENING/DIARY_REACTION/MAX_EVENT等）、
# psychology_state（単独・2心理複合）、group、timed_event_key、target_patternで
# 原稿単位を識別する。SystemTimedEvent.csvには会話結果文と特殊期間の角括弧文を置き、
# PsychologyReactionDialogue側はTimedEvent参照のみとする。新CSVはCSVCryptoCompilerの
# TalkSource/TalkCSV全件処理でTalkDataへ収録する。Hostility + Obedienceの
# 「いまのきもち」本文は原稿未提供のため未登録。Death:crow自体の処理は既存方式を使用する。
